"""add empresa

Revision ID: 077d55a5d55d
Revises: 59dadfa8a234
Create Date: 2025-08-18 21:53:21.878108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077d55a5d55d'
down_revision: Union[str, Sequence[str], None] = '59dadfa8a234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.add_column('colaboradores', sa.Column('empresa_id', sa.UUID(), nullable=False))
    #op.alter_column('colaboradores', 'jornada_padrao',
    #           existing_type=sa.VARCHAR(),
    #           type_=sa.Integer(),
    #          existing_nullable=True)
    op.create_foreign_key(None, 'colaboradores', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'colaboradores', type_='foreignkey')
    #op.alter_column('colaboradores', 'jornada_padrao',
    #           existing_type=sa.Integer(),
    #           type_=sa.VARCHAR(),
    #           existing_nullable=True)
    op.drop_column('colaboradores', 'empresa_id')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
