"""importando tabela colaborador

Revision ID: 59dadfa8a234
Revises: 8a8f27ab1e83
Create Date: 2025-07-30 09:13:44.221851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59dadfa8a234'
down_revision: Union[str, Sequence[str], None] = '8a8f27ab1e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaboradores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('jornada_padrao', sa.String(), nullable=True),
    sa.Column('horario_personalizado', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colaboradores_cpf'), 'colaboradores', ['cpf'], unique=True)
    op.create_index(op.f('ix_colaboradores_id'), 'colaboradores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_colaboradores_id'), table_name='colaboradores')
    op.drop_index(op.f('ix_colaboradores_cpf'), table_name='colaboradores')
    op.drop_table('colaboradores')
    # ### end Alembic commands ###
