"""add jornada e horario_jornada

Revision ID: 672f9211dc85
Revises: d03074628a7e
Create Date: 2025-08-27 11:36:17.645451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672f9211dc85'
down_revision: Union[str, Sequence[str], None] = 'd03074628a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jornadas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('horas_semanais', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jornadas_id'), 'jornadas', ['id'], unique=False)
    op.create_table('horarios_jornada',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dia_semana', sa.String(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('jornada_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('colaboradores', sa.Column('jornada_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'colaboradores', 'jornadas', ['jornada_id'], ['id'])
    op.drop_column('colaboradores', 'horario_personalizado')
    op.drop_column('colaboradores', 'jornada_padrao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colaboradores', sa.Column('jornada_padrao', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('colaboradores', sa.Column('horario_personalizado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'colaboradores', type_='foreignkey')
    op.drop_column('colaboradores', 'jornada_id')
    op.drop_table('horarios_jornada')
    op.drop_index(op.f('ix_jornadas_id'), table_name='jornadas')
    op.drop_table('jornadas')
    # ### end Alembic commands ###
