"""initial migration

Revision ID: fc1045babbf0
Revises: 
Create Date: 2025-11-08 20:46:00.157554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1045babbf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_USER', 'EMPRESA', 'ADMIN', 'COLABORADOR', name='role', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('jornadas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('horas_semanais', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jornadas_id'), 'jornadas', ['id'], unique=False)
    op.create_table('colaboradores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('SUPER_USER', 'EMPRESA', 'ADMIN', 'COLABORADOR', name='role', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='status', native_enum=False), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('jornada_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf', 'empresa_id', name='uq_colaborador_cpf_empresa')
    )
    op.create_index(op.f('ix_colaboradores_cpf'), 'colaboradores', ['cpf'], unique=False)
    op.create_index(op.f('ix_colaboradores_email'), 'colaboradores', ['email'], unique=True)
    op.create_index(op.f('ix_colaboradores_id'), 'colaboradores', ['id'], unique=False)
    op.create_table('horarios_jornada',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dia_semana', sa.String(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('jornada_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horarios_jornada')
    op.drop_index(op.f('ix_colaboradores_id'), table_name='colaboradores')
    op.drop_index(op.f('ix_colaboradores_email'), table_name='colaboradores')
    op.drop_index(op.f('ix_colaboradores_cpf'), table_name='colaboradores')
    op.drop_table('colaboradores')
    op.drop_index(op.f('ix_jornadas_id'), table_name='jornadas')
    op.drop_table('jornadas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
